base_url = "https://limeleaf.net"
title = "Limeleaf Worker Collective | We Build Software"
description = "Limeleaf is a software development cooperative that draws on decades of experience to help teams build software products faster."

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "tags", feed = false },
]
 
[markdown]
highlight_code = true
highlight_theme = "axar"

[extra]
copyright = "Limeleaf Worker Collective, LLC"
