base_url = "https://limeleaf.io"
title = "Limeleaf Worker Collective | We Build Software"
description = "Limeleaf is a software development cooperative that provides Staff-level software engineering and product development for businesses, brands, and startups."

generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
highlight_theme = "axar"

[extra]
copyright = "Limeleaf Worker Collective, LLC"
