base_url = "https://limeleaf-collective.github.io/limeleaf.io"
title = "Limeleaf Worker Collective, LLC"
description = "Limeleaf is a software development cooperative that builds fresh, sustainable, simple tech solutions for small businesses, startups, and nonprofits."
